---

- name: Docker repo is present
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: 0644
  environment: "{{ docker_proxy_env }}"
  when: ansible_os_family == "RedHat"
  become: yes
  
- name: Docker is installed
  package:
    name: docker-ce
    state: present
  environment: "{{ docker_proxy_env }}"
  become: yes

- name: Docker systemd custom directory is present
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: 0755
  become: yes

- name: Proxy configuration is present
  template:
    src: proxy.conf.j2
    dest: /etc/systemd/system/docker.service.d/proxy.conf
  notify:
    - restart docker
  when: docker_http_proxy != "" or docker_https_proxy != "" or docker_no_proxy != ""
  become: yes

- name: Docker daemon is enabled
  service:
    name: docker
    enabled: yes
    masked: no
  become: yes
